### ISSUE TITLE
Not working with UNO + Attiny84-PU

### ISSUE THREAD

**Issue by Labikettedu08** [nadavmatalon/TinyWireS#2]
Hi,

I tried to use example from you library, but the communication seems not working... in the serial monitor, I've always  **Requested 4 bytes, but got 0 bytes**

_Configuration :_
- 1 UNO as Master
- 1 Attiny84-PU
     * 2.2k R between SDA/SCL and +5Vdc as requested)
     * powered by +5Vdc and GND from the UNO
     * CPU freq internal at 8MHz

![Capture d’écran 2020-12-17 132948](https://user-images.githubusercontent.com/63372721/102489541-e60a9c00-406d-11eb-9e95-1421542ee315.jpg)

Any ideas please ?

Thanks in advance
Aurélien

**Comment by Labikettedu08** [comment]
Oh... I forget... I also tried to force the CPU freq to 8MHz via the soft using this parameter :  **#define F_CPU 8000000**
Same issue... Nothing happens

**Comment by nadavmatalon** [comment]
Hi,
I'm sorry, but I've written this library so long ago I can hardly remember anything about it.
That said, 2 things might be worth looking into: 
1. I seem to remember there's a difference between the Attiny84 and Attiny84-PU (could be just the SMD version vs the pinned one, but perhaps not).
2. When you say: "2.2k R between SDA/SCL and +5Vdc as requested)" - is it 1 pull-up resistor for the SDA line to the 5V rail and 1 separate pull-up resistor for the SCL line to the 5V rail? If not, that could be what's causing the problem.
Hope that helps.

**Comment by Labikettedu08** [comment]
Hi again,

Thanks for your fast reply... I finally arrive to let communicate my Attiny84 with my UNO using simply the general Wire library
It's working fine, so no need TinyWireS library :) 

BR

**Comment by nadavmatalon** [comment]
Cool, happy you got it figured out :-)
